### ISSUE TITLE
Add blurHash & lqip to the returned `SanityImageAsset` when using `getImage` or `getImageAsset`

### ISSUE THREAD

**Issue by harrisrobin** [sanity-io/asset-utils#26]
**Is your feature request related to a problem? Please describe.**
Right now, when we use `getImage` or `getImageAsset` we only get the dimensions metadata but are missing other metadata such as blurHash and lqip.

**Describe the solution you'd like**
I can clearly see that data when i query my assets using GROQ. I would like to be able to get this when using `asset-utils` as well. is this possible?

**Describe alternatives you've considered**
I've considered simply querying my assets with GROQ but i would like to avoid this and rely on this library instead.

**Comment by rexxars** [comment]
This library only does client-side operations - LQIP and blurHash are not available without having access to the asset document.
