### ISSUE TITLE
originalFilename not found in getImageAsset function

### ISSUE THREAD

**Issue by ibrhm-mnf** [sanity-io/asset-utils#3]

**Comment by rexxars** [comment]
The readme could probably be a lot clearer about this: This library does not interact with the Sanity content lake (database) in any way.

All functions are synchronous, and only help to resolve information based on asset IDs, paths, URLs and similar - for instance, taking a Sanity asset ID such as `image-someSha1Hash-320x240-png` and returning a more structured record of information, like:
```
{
  _type: 'sanity.imageAsset',
  assetId: 'someSha1Hash',
  extension: 'png',
  metadata: {
    dimensions: {width: 320, height: 240, aspectRatio: 1.33} 
  }
}
```

If you want to retrieve the original filename from the database, you'll have to use a query against the API
