### ISSUE TITLE
originalFilename not present in getFileAsset()

### ISSUE THREAD

**Issue by rienswagerman** [sanity-io/asset-utils#4]
https://sanity-io.github.io/asset-utils/index.html#getfileasset is not returning the originalFilename, although it is included in the options params (originalFilename: true and useVanityName: true), as is documented here https://sanity-io.github.io/asset-utils/interfaces/pathbuilderoptions.html.

**Params**

_src_

```
asset: {_ref: 'file-893ae787544e3999c424bd5082924052795efe8d-pdf', _type: 'reference'}
itemMetaData: {_type: 'itemMetaData', caption: 'First factory design in Den Bosch'}
_key: "f04292f7c88b"
_type: "fileItem"
```

_options_

```
{
apiHost: "https://api.sanity.io"
apiVersion: "1"
cdnUrl: "https://xx9fbq46.apicdn.sanity.io/v1"
dataset: "staging"
gradientMode: false
isDefaultApi: true
isPromiseAPI: true
originalFilename: true
projectId: "xxxxxxx"
url: "https://xx9fbq46.api.sanity.io/v1"
useCdn: false
useProjectHostname: true
useVanityName: true
}
```

**Response**

```
assetId: "893ae787544e3999c424bd5082924052795efe8d"
extension: "pdf"
metadata: {}
path: "files/xxxxx/staging/893ae787544e3999c424bd5082924052795efe8d.pdf"
url: "https://cdn.sanity.io/files/xxxxxx/staging/893ae787544e3999c424bd5082924052795efe8d.pdf"
_id: "file-893ae787544e3999c424bd5082924052795efe8d-pdf"
_type: "sanity.fileAsset"
```

**Query in Vision *does* return originalFilename**

```
*[_type == "project" && _id == "18307598-bda2-420d-9243-396f5e1271de"]{
  "doc": documents[0]{asset->{path,url,_type, extension, originalFilename}}
}

[
  {
    "doc": {
      "asset": {
        "_type": "sanity.fileAsset",
        "extension": "pdf",
        "originalFilename": "20160708 Protix.pdf",
        "path": "files/xxxxxx/staging/893ae787544e3999c424bd5082924052795efe8d.pdf",
        "url": "https://cdn.sanity.io/files/xxxxxxxx/staging/893ae787544e3999c424bd5082924052795efe8d.pdf"
      }
    }
  }
]

```

Probably same issue here https://github.com/sanity-io/asset-utils/issues/3

**Comment by rexxars** [comment]
The readme could probably be a lot clearer about this: This library does not interact with the Sanity content lake (database) in any way.

All functions are synchronous, and only help to resolve information based on asset IDs, paths, URLs and similar - for instance, taking a Sanity asset ID such as `image-someSha1Hash-320x240-png` and returning a more structured record of information, like:
```
{
  _type: 'sanity.imageAsset',
  assetId: 'someSha1Hash',
  extension: 'png',
  metadata: {
    dimensions: {width: 320, height: 240, aspectRatio: 1.33} 
  }
}
```

If you want to retrieve the original filename from the database, you'll have to use a query as you outlined here.

**Comment by rienswagerman** [comment]
Clear. Thanks.

Note: When querying the asset with the 'originalFilename' in the list of values to be returned it does not make a difference if 'originalFilename: true' is specified in the options for getFileAsset() or not .

**Comment by doublejosh** [comment]
It took some digging to find the final URL format. It's just a vanity URI... slap the original filename on the end with a backslash.

````${file?.asset?.url}/${file?.asset?.originalFilename}````

Format...
`<https://cdn.sanity.io/images/><projectId>/<dataset>/<hashedFileName>/<originalFilename>?<params>`

https://www.sanity.io/answers/how-to-request-an-image-from-sanity-with-its-original-filename-instead-of-a-hash
